Two fixes
Holfz/Steam-Account-Creator pull request #7
Opened 2019-02-07 13:20 UTC by idubs

The clipboard action wasn't threadsafe and would throw a runtime error when called from any non-UI thread.
The WriteIntoFile function didn't save the alias. The writer also was colon delimited but since the passwords had a chance to contain a colon that didn't make much sense, tab delimited seemed like a better option.

2019-02-09 16:24 UTC, Holfz commented
Thanks! for pulling request... But format of mail + ":" + pass is fine

2019-02-09 16:25 UTC, Holfz requested changes
FileManager.cs don't need to edit for format

2019-02-10 18:31 UTC, idubs commented
Are you able to login to steam with just the email?

2019-02-10 18:34 UTC, 00110000 commented
> Thanks! for pulling request... But format of mail + ":" + pass is fine

![image](https://user-images.githubusercontent.com/16885744/52537795-6a997e80-2d62-11e9-9629-568131be25cb.png)

you definitely can't login with an email, are you sure mail:pass is fine?

2019-02-10 18:38 UTC, Holfz commented
Sorry for that. i only edit the mail system and create like one account. Merging Pull Request..

2019-02-10 18:38 UTC, merged